base_platform: b-ubuntu-1204
topology: tier
api_fqdn: chef-tier.lxc
mount:
  - /oc oc
  - /dev-shared dev-shared
package:
  server: /dev-shared/chef-packages/ec/private-chef_11.1.1-1.ubuntu.12.04_amd64.deb
  reporting: /dev-shared/chef-packages/ec/opscode-reporting_1.1.0-1.ubuntu.12.04_amd64.deb
  push-jobs-server: /dev-shared/chef-packages/ec/opscode-push-jobs-server_1.1.0-1.ubuntu.12.04_amd64.deb
  manage: /dev-shared/chef-packages/ec/opscode-manage_1.1.1-1.ubuntu.12.04_amd64.deb
server:
  be-tier.lxc:
    role: backend
    ipaddress: 10.0.3.202
    bootstrap: true
  fe1-tier.lxc:
    role: frontend
    ipaddress: 10.0.3.203
#  fe2-tier.lxc:
#    role: frontend
#    ipaddress: 10.0.3.204
